# Generated by Django 2.2.5 on 2019-11-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_auto_20191107_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='last_message',
            field=models.IntegerField(default=0, verbose_name='ID последнего сообщения'),
        ),
    ]
