# Generated by Django 2.2.5 on 2019-10-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('nick', models.CharField(blank=True, default='', max_length=31)),
                ('avatar', models.BinaryField(blank=True, default='')),
            ],
        ),
    ]
