# Generated by Django 2.2.5 on 2019-10-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='new_messages',
            field=models.IntegerField(default=0),
        ),
    ]
